version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: jointeste
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    image: meu-backend
    container_name: meu-backend
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_DATABASE: jointeste
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local